from enum import Enum

class TematicEnum(Enum):
    PRADERA   =   "Pradera"
    PIANO     =   "Piano"
    DESIERTO  =   "Desierto"
    NIEVE	  =   "Nieve"
    PIRATA    =   "Pirata"
    SELVA     =   "Selva"
    ÉPICO     =   "Épico"
    TENEBROSO =   "Tenebroso"
    AGUA      =   "Agua"
    ASIATICO  =   "Asiático"
    ROCK      =   "Rock"
    POP       =   "Pop"
    TECNO     =   "Tecno"

class TematicDrumEnum(Enum):
    PRADERA   =   "Pradera"
    PIANO     =   "Piano"
    DESIERTO  =   "Desierto"
    NIEVE	  =   "Nieve"
    PIRATA    =   "Pirata"
    SELVA     =   "Selva"
    ÉPICO     =   "Épico"
    TENEBROSO =   "Tenebroso"
    AGUA      =   "Agua"
    ASIATICO  =   "Asiático"
    ROCK      =   "Rock"
    POP       =   "Pop"
    TECNO     =   "Tecno"
    DEMBOW     =   "Dembow"