notes_pitch = {
    "BassDrum": 36,
    "SideStick": 37,
    "AcousticSnare": 38,  
    "AcousticClap": 39,
    "ElectricSnare": 40,
    "LowFloorTom": 41,
    "ClosedHiHat ": 42,
    "HighFloorTom": 43,
    "PedalHiHat": 44,
    "LowTom": 45,
    "OpenHi-Hat": 46,
    "LowMidTom": 47,
    "HiMidTom ":48,
    "CrashCymbal": 49,
    "HighTom": 50,
    "RideCymbal": 51,
}
